# Site settings

title: John McKim
email: contact@johncmckim.me
author:
  name: "John McKim"
  email: contact@johncmckim.me
  uri: "http://johncmckim.me"

description: >
  Occasional writings

baseurl: ""
url: "http://johncmckim.me"
avatar: avatar.jpeg
feed:
  path: feed.xml

blog_url:               "https://medium.com/@johncmckim"
medium_username:        "@johncmckim"
twitter_username:       johncmckim
github_username:        johncmckim
stackoverflow_username: 937577/john-mckim
linkedin_username:      johncmckim
#google_plus_username
#facebook_username:    johncmckim
#dribbble_username:    example

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-feed
