# Site settings
paginate: 8
paginate_path: "/blog/page:num/"

title: John McKim
email: contact@johncmckim.me
author:
  name: "John McKim"
  email: contact@johncmckim.me
  uri: "https://johncmckim.me"

job:
  prefix: the
  title: VP of Product & Technology

employer:
  name: A Cloud Guru
  uri: https://acloud.guru

description: >
  VP of Product & Technology at A Cloud Guru, Serverless enthusiast, writer, home cook and terrible gardener.

baseurl: ""
url: "https://johncmckim.me"
avatar: avatar.jpeg
feed:
  path: feed.xml

blog_url:               https://medium.com/@johncmckim
medium_username:        "@johncmckim"
twitter_username:       johncmckim
# github_username:        johncmckim
# stackoverflow_username: 937577/john-mckim
linkedin_username:      johncmckim
#google_plus_username
#facebook_username:    johncmckim
#dribbble_username:    example

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate